name: Auto Add NSOC'26 Label

on:
  issues:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add NSOC'26 label
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: ["NSOC'26"]
            });